### ISSUE TITLE
Modify Installation section

### ISSUE THREAD

**Issue by Youpit44** [X-CASH-official/cryptonote-nodejs-pool#1]
**In paragraph** : [1) Downloading & Installing](https://github.com/X-CASH-official/cryptonote-nodejs-pool#1-downloading--installing)
> Clone the repository and run npm update for all the dependencies to be installed:
> 
> git clone https://github.com/dvandal/cryptonote-nodejs-pool.git pool
> cd pool
> 
> npm update

Modify git clone address to "**https://github.com/X-CASH-official/cryptonote-nodejs-pool.git**"

Thank you ;-)

**Comment by X-CASH-official** [comment]
Thank you for pointing this typo out for us
